### ISSUE TITLE
Poorly parallelized and slow gauss2d_fit function

### ISSUE THREAD

**Issue by taylorbell57** [GalagaBits/JWST-FGS-Spelunker#42]
Because the `gauss2d_fit` function is so slow, I can't tell if the function call has crashed or it is just taking a long time since there is no progress bar. I can submit a pull request to add a progress bar using `tqdm` which I've already got setup on my local branch which partially resolves this issue.

However, in investigating this issue further I noticed that you're currently using ray to parallelize each individual fit rather than running multiple fits in parallel. Each individual fit takes far less than a second, so this method of parallelization offers little-to-no gains (in fact, using a tool like `htop` I can see that regardless of what I set `ncpus` to, the function only really uses ~1 thread since it finishes too fast to use any more threads). For reference when running the `fgs-spelunker-and-tsos.ipynb` demo notebook, the loop at line [spelunker.py#L1260](https://github.com/GalagaBits/JWST-FGS-Spelunker/blob/fc769668ea39efe4c759afafe7d4b680e48f681b/src/spelunker.py#L1260) took me 8m4s with the full 28 threads available on my CPU (a desktop Intel i7-14700K) and 7m51s with only 1 thread, while the loop at [spelunker.py#L1272](https://github.com/GalagaBits/JWST-FGS-Spelunker/blob/fc769668ea39efe4c759afafe7d4b680e48f681b/src/spelunker.py#L1272) took 18m46s with 28 threads and 19m04s with only 1 thread. What you need to do is setup an asynchronous collection of threads that can fit individual frames in parallel which should offer roughly linear scaling in speed-up with the number of threads used (that is, 2 threads should give ~2x speed-up, and 10 threads should give ~10x speed-up), while my testing above showed basically no change in speed with 28 threads vs 1 thread. I'm not immediately sure how to do this with `ray` but have done this with Python's built-in package `multiprocessing` over in [Eureka](https://github.com/kevin218/Eureka) (see for example, [eureka.S3_data_reduction.background.BGsubtraction()](https://github.com/kevin218/Eureka/blob/4e12d23d1b205520851ad92239632dc994936d4c/src/eureka/S3_data_reduction/background.py#L19)).

As a reminder, this is not really related to the review of your JOSS paper and doesn't need to be resolved before that paper is accepted. I'm just now an invested future user wanting to help improve a wonderfully useful package!

**Comment by GalagaBits** [comment]
I fixed the issue and its much faster now. Will update soon

**Comment by GalagaBits** [comment]
The latest update V1.1.14 fixes this issue.

**Comment by taylorbell57** [comment]
FYI, this issue still isn't fully resolved for me - my numbers above had been for the WASP-39b calculations which I didn't specify and might have caused some confusion.

Trying the HAT-P-14b fit cell, I get 3m25s for the first loop and 13s for the second loop with 28 CPU threads, while for a single thread I get 3m11s for the first loop and 6m5s for the second loop. And going back to the WASP-39b cell, I get 8m36s for the first loop and 34s for the second loop with 28 CPU threads, while for a single thread I get 7m47s for the first loop and 18m44s for the second loop.

So your tweak did greatly improve the speed and parallelization of the second loop (with almost perfectly linear scaling in speed-up with `ncpus`), but the first loop still doesn't seem well parallelized.

**Comment by GalagaBits** [comment]
Ah okay, I will improve the first loop. I have been trying to parallelize it with ray. I might need to split the array into chunks then run the ray parallelization. Do you think that can work?

**Comment by taylorbell57** [comment]
That is a possibility, yeah. You could also experiment with making the array a global variable which would avoid the duplication of the array for each thread, but global variables can also be risky.

**Comment by GalagaBits** [comment]
I found a solution that is very promising. I will update soon, and it fixes the issue. Now you can run 100000 frames in under a minute.

**Comment by GalagaBits** [comment]
@taylorbell57, Okay, the update to v1.1.16 is out with even better performance than before!

**Comment by GalagaBits** [comment]
So, its even faster than before, but I think the same parallelization issue with the first loop is still there. Its even faster with fewer cores for the first loop. Perhaps there's more room for optimization, or its something to do with how `ray` works.

**Comment by GalagaBits** [comment]
In `htop`, more cpu usage is being used with higher core counts, but brings a greater time for the first loop.

**Comment by GalagaBits** [comment]
I tested it a tiny bit, and it seems like without using `ray`, fitting 100000 frames takes 4 minutes. With ray, I get the following: 
- 5 min at 2 cores
- 1 min 30 at 4 cores
- 1 min at 6 cores 
- 59 at 8 cores
- 58 at 10 cores 

These are the total times. I think ray works as expected, and there is further optimization to be done. `tqdm` is probably not optimized for `ray`, and there exists a separate experimental ray instance called `tqdm_ray` from `ray.experimental`.

**Comment by GalagaBits** [comment]
For now, I will close this issue
